# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa63564801f50bfb463fd7ec714f71716d95da86910b76cde5b67148a369adb49c76febfa7829209f56d2acecbce1e3ae9663a0330867218105b93b8ffaed26

test:
  secret_key_base: 0cbcb1bb7f4f8156cda3f9f58e4f7b795c3ffd250415d58622131a6de905898afaac704c4b7c29f2b3485ee03ba9916fdf1ae9f282baab630da1f7e44d3d95dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
